services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      broker:
        condition: service_healthy

  consumer:
    build: .
    container_name: consumer
    volumes:
      - .:/app
    depends_on:
      broker:
        condition: service_healthy

  redis:
    image: redis
    container_name: redis

  snapshot_updater:
    build: .
    container_name: snapshot_updater
    volumes:
      - .:/app
    depends_on:
      broker:
        condition: service_healthy
      redis:
        condition: service_started
    command: python snapshot_updater.py


  broker:
    image: apache/kafka:latest
    container_name: broker
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      KAFKA_LOG_RETENTION_MS: "-1"
      KAFKA_LOG_RETENTION_BYTES: "-1"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  kafka_data:
